TRAIN:
  batch_size: 256
  epochs: 200
  accum_iter: 2
  log_freq: 100  # log information every 100 iterations

MODLE:
  model: mae_vit_base_patch16
  height: 160
  width: 240
  size: 224
  mask_ratio: 0.75
  norm_pix_loss: False

OPT:
  weight_decay: 0.05
  lr:
  blr: 0.00015
  min_lr: 1e-08
  warmup_epochs: 20

DATA:
  output_dir: results
  device: cuda
  seed: 0
  resume: ''
  start_epoch: 0
  root: ../../../dataset/dl/unlabeled/
  list_path: list/unlabeled.txt

DIST:
  num_workers: 16
  pin_mem: True