TRAIN:
  batch_size: 128
  epochs: 400
  accum_iter: 4
  log_freq: 200  # log information every 100 iterations

MODLE:
  model: mae_vit_base_patch16
  height: 160
  width: 240
  input_size: 224
  mask_ratio: 0.75
  norm_pix_loss: False

OPT:
  weight_decay: 0.05
  lr:
  blr: 0.00015
  min_lr: 1e-08
  warmup_epochs: 5

DATA:
  output_dir: results
  device: cuda
  seed: 0
  resume: 'results/mae_pretrain/resume00/checkpoint-199.pth'
  start_epoch: 0
  root: ../../../dataset/dl/
  list_path: list/unlabeled.txt
  flip: 0.0

DIST:
  num_workers: 10
  pin_mem: True