TRAIN:
  batch_size: 10
  epochs: 300
  accum_iter: 0
  log_freq: 80  # log information every 100 iterations
  opt: AdamW  # sgd or adamw
  test_log_freq: 10
  test: True

MODLE:
  model: cvitvp
  height: 160
  width: 240
  input_size: 224
  norm_pix_loss: False
  skip: True
  simvp_weight: results/simvpv2/dl_simvp_in128_lr002_ep130/last.pth

SEGHEAD:
  seghead: hrnet48
  seghead_weight: results/unet/ep300/best.pth
  classifier:
  bn_type: torchbn
  proj_dim: 256
  bottle_type: 2  # orginal one
  bottle_conv: 3

OPT:
  weight_decay: 0.005
  momentum: 0.9
  nesterov: True
  lr:
  blr: 0.002  # 0.00015
  min_lr: 1e-08
  warmup_epochs: 2
  eff_batch_adjust: 11  # equal to adjusting learning rate

DATA:
  output_dir: results
  num_frames: 11
  device: cuda
  seed: 0
  resume: ''
  start_epoch: 0
  root: ../../../dataset/dl/
  num_cls: 49  # 48 + 1 (background)

AUG:
  flip: 0.5
  reverse: 0.05

DIST:
  num_workers: 2
  pin_mem: True